
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroServiceDatabase
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    rest:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #default-schema:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9002